In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,mean_squared_error,r2_score
from smodel = RandomForestClassifier()
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)klearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [46]:
iris = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
Y = iris['variety']
X = iris.drop('variety',axis=1)
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=10)


In [3]:
model = RandomForestClassifier()
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)

In [4]:
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[14  0  0]
 [ 0 16  1]
 [ 0  1 13]]
0.9555555555555556


In [8]:
from sklearn.tree import export_text
print(export_text(model.estimators_[0]))

|--- feature_3 <= 0.70
|   |--- class: 0.0
|--- feature_3 >  0.70
|   |--- feature_3 <= 1.65
|   |   |--- feature_2 <= 5.00
|   |   |   |--- class: 1.0
|   |   |--- feature_2 >  5.00
|   |   |   |--- feature_1 <= 2.75
|   |   |   |   |--- class: 1.0
|   |   |   |--- feature_1 >  2.75
|   |   |   |   |--- class: 2.0
|   |--- feature_3 >  1.65
|   |   |--- feature_3 <= 1.75
|   |   |   |--- feature_1 <= 2.75
|   |   |   |   |--- class: 2.0
|   |   |   |--- feature_1 >  2.75
|   |   |   |   |--- class: 1.0
|   |   |--- feature_3 >  1.75
|   |   |   |--- feature_0 <= 5.95
|   |   |   |   |--- feature_2 <= 4.85
|   |   |   |   |   |--- class: 1.0
|   |   |   |   |--- feature_2 >  4.85
|   |   |   |   |   |--- class: 2.0
|   |   |   |--- feature_0 >  5.95
|   |   |   |   |--- class: 2.0



In [47]:
wine=pd.read_csv("C:\\Users\\Admin\\Downloads\\winequality-red.csv",sep=';')
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [48]:
Y = wine['quality']
X = wine.drop('quality',axis=1)
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=10)

In [14]:
model = RandomForestClassifier()
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)

In [15]:
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[  0   1   1   0   0   0]
 [  0   0  11   5   0   0]
 [  0   2 162  43   3   0]
 [  0   1  48 122  12   0]
 [  0   0   1  25  32   0]
 [  0   0   0   6   5   0]]
0.6583333333333333


In [16]:
from sklearn.tree import export_text
print(export_text(model.estimators_[0]))

|--- feature_2 <= 0.30
|   |--- feature_9 <= 0.56
|   |   |--- feature_1 <= 0.55
|   |   |   |--- feature_0 <= 7.40
|   |   |   |   |--- feature_1 <= 0.48
|   |   |   |   |   |--- feature_7 <= 1.00
|   |   |   |   |   |   |--- feature_1 <= 0.35
|   |   |   |   |   |   |   |--- feature_7 <= 0.99
|   |   |   |   |   |   |   |   |--- class: 4.0
|   |   |   |   |   |   |   |--- feature_7 >  0.99
|   |   |   |   |   |   |   |   |--- class: 2.0
|   |   |   |   |   |   |--- feature_1 >  0.35
|   |   |   |   |   |   |   |--- feature_5 <= 9.50
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_5 >  9.50
|   |   |   |   |   |   |   |   |--- class: 3.0
|   |   |   |   |   |--- feature_7 >  1.00
|   |   |   |   |   |   |--- feature_9 <= 0.52
|   |   |   |   |   |   |   |--- class: 2.0
|   |   |   |   |   |   |--- feature_9 >  0.52
|   |   |   |   |   |   |   |--- class: 3.0
|   |   |   |   |--- feature_1 >  0.48
|   |   |   |   |   |--- feature_6 <= 63.00
|   

In [49]:
from sklearn.svm import SVC,SVR

In [50]:
model = SVC()
model.fit(X_train,Y_train)

SVC()

In [19]:
Y_pred = model.predict(X_test)

In [20]:
print(accuracy_score(Y_test,Y_pred))

0.46458333333333335


In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [54]:
model = KNeighborsClassifier(n_neighbors=10)
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)
print(accuracy_score(Y_test,Y_pred))

0.5145833333333333


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [22]:
auto.def

SyntaxError: invalid syntax (4149428179.py, line 1)

In [23]:
auto.head()

0  1      2      3       4     5   6  7                          8
0  18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1  15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2  18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3  16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4  17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino

In [24]:
auto.columns = ['mpg',
'cylinders',
'displacement',
'horsepower',
'weight',
'acceleration',
'model',
'origin',
'car'
]

In [25]:
from sklearn.preprocessing import LabelEncoder

In [28]:
le = LabelEncoder()
auto['car'] = le.fit_transform(auto['car'])

In [29]:
auto['horsepower']=auto['horsepower'].str.replace("?","0")
auto['horsepower'] = auto['horsepower'].astype(float)

C:\Users\Admin\AppData\Local\Temp\ipykernel_6508\175874402.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  auto['horsepower']=auto['horsepower'].str.replace("?","0")


In [30]:
X = auto.drop('mpg',axis=1)
Y= auto['mpg']

In [31]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=10)

In [36]:
model = SVC()
model.fit(Y_train,X_train)

ValueError: Expected 2D array, got 1D array instead:
array=[31.  10.  29.5 18.6 26.  25.4 31.6 25.  22.  20.6 11.  19.9 15.  25.5
 24.  17.  34.3 19.  15.5 19.8 31.  19.2 46.6 36.1 28.  24.3 17.  44.3
 26.  36.  30.9 20.  15.  18.  23.9 26.6 19.2 12.  31.3 16.5 20.  24.
 27.2 12.  14.  19.  23.  21.5 25.  29.  14.  18.2 38.  30.  26.  14.
 34.5 25.  20.2 15.5 25.  29.  34.2 13.  16.  18.  28.  34.1 23.  36.4
 27.  30.  30.5 33.5 28.  15.  17.5 18.  14.  31.  23.6 27.4 35.1 38.1
 18.5 29.  27.  14.  22.3 17.  22.  17.7 15.  26.4 32.4 19.  27.  35.
 24.  25.8 17.6 21.1 24.  18.  13.  19.4 20.2 16.  19.  33.  24.2 24.5
 32.  25.  36.  28.4 25.  27.9 14.  15.  11.  13.  14.   9.  34.4 13.
 23.7 16.  20.  27.  14.5 20.8 16.5 26.5 18.  30.  27.  28.  25.1 13.
 16.  32.7 37.2 23.  38.  16.  15.  24.  16.2 27.5 15.  32.9 18.  29.9
 43.4 29.8 23.  12.  11.  13.  25.  20.2 43.1 41.5 14.  26.8 31.  19.
 38.  44.  12.  14.  29.  25.4 40.8 31.  23.  23.9 28.  19.1 30.  24.
 28.1 23.8 17.  16.  26.  15.  20.  18.5 18.  29.8 26.  30.5 12.  16.
 26.  26.  37.  33.5 27.2 19.  14.  26.  24.5 13.  32.8 16.  26.  23.2
 15.5 28.  28.8 39.1 17.  16.  13.  19.4 16.9 20.6 29.5 18.  32.  19.
 24.  34.5 32.  31.5 13.  36.  36.1 13.  22.  14.  27.  20.2 18.5 28.
 25.  32.2 14.  15.  16.  17.6 30.  37.7 29.  21.5 14.  22.  36.  22.
 23.  34.  18.  19.  13.  24.  22.4 39.  35.  30.  32.4 18.  29.  14.
 20.5 13.  14.  27.  17.5 16.  20.  34.  37.  22.  20.  17.5].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [33]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=10)

In [34]:
model = SVC()

In [35]:
model.fit(X_train,Y_train)

ValueError: Unknown label type: 'continuous'

In [38]:
model = RandomForestClassifier()


In [39]:
model.fit(X_train,Y_train)


ValueError: Unknown label type: 'continuous'

In [40]:
from sklearn.svm import SVC,SVR

In [41]:
model = SVC()

In [42]:
model.fit(X_train,Y_train)

ValueError: Unknown label type: 'continuous'

In [55]:
import pandas as pd

In [56]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [57]:
def preprocess(df,outputcolumn):
    X=df.drop(outputcolumn,axis=1)
    Y=df[outputcolumn]
    X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=10)
    return (X_train,X_test,Y_train,Y_test)

In [62]:
def selectAlgo(X_train,X_test,Y_train,Y_test):
    model = {}
    model['DecisionTee'] = DecisionTreeClassifier()
    model['RandomForest'] = RandomForestClassifier()
    model['SupportVector']= SVC()
    model['Knn'] = KNeighborsClassifier()
    
    for model_name,m in model.items():
        print(model_name,'is fitting')
        m.fit(X_train,Y_train)
        Y_pred = m.predict(X_test)
        print(model_name,accuracy_score(Y_test,Y_pred))

In [63]:
res = preprocess(pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'),'variety')

In [64]:
selectAlgo(res[0],res[1],res[2],res[3])

DecisionTee is fitting
DecisionTee 0.9777777777777777
RandomForest is fitting
RandomForest 0.9777777777777777
SupportVector is fitting
SupportVector 1.0
Knn is fitting
Knn 0.9777777777777777


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [65]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [66]:
breast_cancer = load_breast_cancer()
X = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)
y = pd.Categorical.from_codes(breast_cancer.target, breast_cancer.target_names)

In [67]:
encoder = LabelEncoder()
binary_encoded_y = pd.Series(encoder.fit_transform(y))

In [68]:
train_X, test_X, train_y, test_y = train_test_split(X, binary_encoded_y, random_state=1)
print(X)

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mea

In [69]:
classifier = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=1),
    n_estimators=200
)
classifier.fit(train_X, train_y)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=200)

In [70]:
predictions = classifier.predict(test_X)

In [71]:
confusion_matrix(test_y, predictions)

array([[86,  2],
       [ 3, 52]], dtype=int64)

In [72]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

In [73]:
train_data = pd.read_csv("C:/pythonall/titanic/train.csv")
test_data = pd.read_csv("C:/pythonall/titanic/test.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:/pythonall/titanic/train.csv'